version: '2'
services:

  base:
    build: ./slack-api-export
    image: social-search-app

  php-fpm:
    build:
      context: ./slack-api-export
      dockerfile: Dockerfile.fpm
    environment:
      - SLACK_CLIENT_ID
      - SLACK_CLIENT_SECRET
      - SLACK_CLIENT_REDIRECT_URI
    links:
      - mongo
    volumes:
      - ./logs/http:/var/www/slack-api-export/var/logs

  web:
    build:
      context: ./slack-api-export
      dockerfile: Dockerfile.nginx
    links:
      - php-fpm
    ports:
      - 80:8080
    volumes:
      - ./logs/nginx:/var/log/nginx/

  console:
    build:
      context: ./slack-api-export
      dockerfile: Dockerfile.console
    depends_on:
      - base
    links:
      - mongo
    volumes:
      - ./logs/console:/opt/slack-api-export/var/logs
      - ./export:/opt/slack-api-export/var/export

  mongo:
    image: mongo
    volumes:
      - ./mongo:/data/db
