version: '2'
services:

  base:
    build: ./slack-api-export
    image: slackapiexport_base

  php-fpm:
    build:
      context: ./slack-api-export
      dockerfile: Dockerfile.fpm
    environment:
      - SLACK_TOKEN
      - SLACK_CLIENT_ID
      - SLACK_CLIENT_SECRET
      - SLACK_CLIENT_REDIRECT_URI
    links:
      - mongo
    volumes:
      - ./docker/slack_export/messages:/var/www/slack-api-export/var/messages
      - ./docker/slack_export/cache:/var/www/slack-api-export/var/cache
      - ./docker/slack_export/logs:/var/www/slack-api-export/var/logs
      - ./docker/slack_export/sessions:/var/www/slack-api-export/var/sessions

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    links:
      - php-fpm
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx:/var/log/nginx/

  console:
    build:
      context: ./slack-api-export
      dockerfile: Dockerfile.console
    depends_on:
      - base
    links:
      - mongo
    volumes:
      - ./docker/slack_export:/opt/slack-api-export/var

  mongo:
    image: mongo
    volumes:
      - ./docker/mongo:/data/db
