version: '2'
services:

  base:
    build: ./slack-api-export
    image: social-search-app

  http:
    build:
      context: ./slack-api-export
      dockerfile: Dockerfile.http
    environment:
      - SLACK_CLIENT_ID
      - SLACK_CLIENT_SECRET
      - SLACK_CLIENT_REDIRECT_URI
    depends_on:
      - base
    links:
      - mongo
    ports:
      - 8000:8000
    volumes:
      - ./logs/http:/opt/slack-api-export/var/logs

  console:
    build:
      context: ./slack-api-export
      dockerfile: Dockerfile.console
    depends_on:
      - base
    links:
      - mongo
    volumes:
      - ./logs/console:/opt/slack-api-export/var/logs
      - ./export:/opt/slack-api-export/var/export

  mongo:
    image: mongo
    volumes:
      - ./mongo:/data/db
