version: '2'
services:

  base:
    build: ./slack-api-export
    image: slackapiexport_base

  php-fpm:
    build:
      context: ./slack-api-export
      dockerfile: Dockerfile.fpm
    image: socialsearch_slack_php-fpm
    environment:
      - SLACK_TOKEN
      - SLACK_CLIENT_ID
      - SLACK_CLIENT_SECRET
      - SLACK_CLIENT_REDIRECT_URI
      - SOCIAL_SEARCH_API=http://social-search:8080
    links:
      - mongo
      - social-search
    volumes:
      - ./docker/slack_export/messages:/var/www/slack-api-export/var/messages
      - ./docker/slack_export/cache:/var/www/slack-api-export/var/cache
      - ./docker/slack_export/logs:/var/www/slack-api-export/var/logs
      - ./docker/slack_export/sessions:/var/www/slack-api-export/var/sessions

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: socialsearch_slack_nginx
    links:
      - php-fpm
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx:/var/log/nginx/

  console:
    build:
      context: ./slack-api-export
      dockerfile: Dockerfile.console
    image: socialsearch_slack_console
    environment:
      - SOCIAL_SEARCH_API=http://social-search:8080
    depends_on:
      - base
    links:
      - mongo
      - social-search
    volumes:
      - ./docker/slack_console:/opt/slack-api-export/var

  mongo:
    image: mongo
    volumes:
      - ./docker/mongo:/data/db

  elasticsearch:
    image: elasticsearch
    volumes:
      - ./config/elasticsearch:/usr/share/elasticsearch/config
      - ./docker/elasticsearch:/usr/share/elasticsearch/data

  social-search:
    build:
      context: ./social-search
      args:
        - MC_API_KEY
        - ES_HOSTNAME=elasticsearch
        - ES_PORT=9200
    image: socialsearch_social-search
    ports:
      - "8081:8080"
    links:
      - elasticsearch

  bot:
    build:
      context: ./knowbot-slackbot
    image: socialsearch_bot
    environment:
      - TOKEN=${SLACK_BOT_TOKEN}
      - BOT_PLATFORM=slack_ci
      - SOCIAL_SEARCH_API=http://social-search:8080
    volumes:
      - ./docker/bot/json_db:/opt/bot/json_db
    links:
      - social-search
